### ISSUE TITLE
Fedex Shipping Error: ERROR - 1000: Authentication Failed

### ISSUE THREAD

**Issue by edgardoburgos** [spree-contrib/spree_active_shipping#11]
Hi everyone, Im having a problem with Spree_active_shipping. I get a “Shipping Error: ERROR - 1000: Authentication Failed” error when checking out. Im using fedex, I added my Fedex credentials to lib/active_shipping_configuration.rb. I cant seem to get it to work, I’ve tried for about 2 weeks. Anyone have this issue or know how to configure spree_active_shipping? Thank you for your guidance in advance.

**Comment by vishal0909** [comment]
I got the same issue. If you found any solution then please let me know.

**Comment by visoft** [comment]
I'm experiencing the same issue, could you please let me know if you found a solution.

**Comment by ime-syncoria** [comment]
I am also facing same issue
