### ISSUE TITLE
Dimensional Weight shift UPS/FedEx will require dimensions reported on all products

### ISSUE THREAD

**Issue by amandablum** [spree-contrib/spree_active_shipping#199]
UPS, FedEx are eliminating weight based shipping in Q12015, and their APIs will accept dimensions for each product and do the algorithm for calculating dimensional weight on the entire package on their respective ends, IF Spree reports the dimensions of each product. 

Active Shipping needs to be updated to report dimensions of each product for anyone offering actual shipping rates, rather than flat rate, table rate or freeship. 

Is anyone working on this?

**Comment by mleglise** [comment]
Has anyone made progress on this since December? I'm about to start work on it if not.

**Comment by IrvinFan** [comment]
@mleglise Please go ahead. I don't think anobody is working on it.

**Comment by mleglise** [comment]
I've added a method `convert_package_to_dimensions_array` that, by default, continues the current behavior of not providing any dimensions.

When overridden, it can be tailored to the particular needs of the application.

https://github.com/mleglise/spree_active_shipping/commit/ff75287402996b402140f65309b3e58c81efb20a

**Comment by JDutil** [comment]
Nice I believe specs are passing again now if you want to submit a PR.

**Comment by jspizziri** [comment]
@JDutil, it looks like you were on top of this issue. a PR has been submitted, would you please give it a quick glance and make sure its behaving as it should?

**Comment by JDutil** [comment]
@jspizziri the PR looks fine to me, but I don't use or work on this extension anymore so I don't have time for it.

**Comment by jspizziri** [comment]
@JDutil, I understand, I'm just trying to go through all the old PR's and issues to clean them up. Since you were the last person to be in the know I wanted to check with you.

**Comment by jspizziri** [comment]
@mleglise what was the status of this?

**Comment by mleglise** [comment]
The method `Spree::Calculator::Shipping::ActiveShipping::Base.convert_package_to_dimensions_array` is available in branches `2-4-stable`, `3-0-stable`, and `master`. It's there to be overridden by individual projects that want to compute their own package dimensions. It's not a perfect fix for this problem, just a stop-gap hook. Seeing no other recent activity on this issue, I am comfortable with closing it until a better solution is presented.
