### ISSUE TITLE
PG::UndefinedTable: ERROR:  relation "spree_product_packages" does not exist

### ISSUE THREAD

**Issue by MisinformedDNA** [spree-contrib/spree_active_shipping#202]
Did a clean checkout, added the `spree_active_shipping` gem and then went to edit a product and got this error. This may be beyond me, but I'm willing to try and help create a PR if I can get some direction.

![undefined product package](https://cloud.githubusercontent.com/assets/1784452/5711297/e2d2342c-9a6e-11e4-89f2-e6ac62a5ddd1.png)

**Comment by futhr** [comment]
1, It says "spree_product_package does not exist", so first of all did you forgot to run the migrations? 
2, Which spree version do you use?

**Comment by MisinformedDNA** [comment]
Migration are run. Running Spree 2.4.3.beta.

There are [two warnings](https://github.com/spree-contrib/spree_active_shipping/issues/200) on WEBrick startup. I don't know if that's somehow related.

**Comment by IrvinFan** [comment]
Did you install the migrations in your app before running?
```
rake spree_active_shipping_extension_engine:install:migrations
```

**Comment by MisinformedDNA** [comment]
Bah! That was it. I hang my head in n00b shame. I really appreciate the quick help!

**Comment by JDutil** [comment]
You can also do the following to ensure all your extension migrations are up to date at the same time: 
```
rake railties:install:migrations
```
