### ISSUE TITLE
We are unable to calculate shipping rates for the selected items

### ISSUE THREAD

**Issue by westlakem** [spree-contrib/spree_active_shipping#208]
There is no indicator when this happens what the issue is... Nothing in the web console or in the terminal.  Not very helpful when trying to debug why this is happening

**Comment by brandon-a-hay** [comment]
I believe it gets displayed as a flash message.

**Comment by westlakem** [comment]
still doesn't tell me what's wrong 

     On Sunday, March 1, 2015 5:09 PM, Brandon Hay <notifications@github.com> wrote:
   

 I believe it gets displayed as a flash message.—

**Comment by chriscarpenter12** [comment]
I am also currently dealing with this, and can't pinpoint where my error may be. Trying to setup US and Canadian shipping with UPS. Double checked my zones and I have ```config[:track_inventory_levels] = false```  as well as Shipping Calculators defined for my zones (United States and Canada). The error is not very helpful.

Does anyone know how to debug this to pinpoint where my issue is?

**Comment by brandon-a-hay** [comment]
Is the zip code of the stock location from where you're purchasing the
product a valid zip code?

**Comment by chriscarpenter12** [comment]
If you are referring to the business address in Configuration > Stock Locations > Default yes it is correct. I have double checked the address, city, state, zip and country.

Or the address used in the checkout process? It is my home address and know the address, city, state, zip and country are correct.

**Comment by brandon-a-hay** [comment]
Yeah that's what I meant. I've had the problem and that was the solution.
Sorry man

**Comment by chriscarpenter12** [comment]
I figured out my own issue if it helps anyone else. I had items in my cart before installing the spree_active_shipping gem and never cleared my cart before testing with the new gem. It never created the associated row in spree_shipments for my current cart and that's why it was failing in the checkout. I cleared the cart, added new items and it worked right away. Should have thought of this first.

Should there be a migration run to bring in active open carts?

**Comment by brandon-a-hay** [comment]
Good find. When I installed Spree it automatically added the active
shipping gem so this was never an issue.

**Comment by jspizziri** [comment]
Is this issue resolved?

**Comment by chriscarpenter12** [comment]
@jspizziri I resolved my own issue. I'm not sure if @westlakem ever did.

**Comment by jspizziri** [comment]
@westlakem, did you resolve your issue?
