### ISSUE TITLE
3.0 Branch

### ISSUE THREAD

**Issue by jspizziri** [spree-contrib/spree_active_shipping#210]
I see that the gemspec file in master has been updated for 3.0.0.beta. Now that spree 3.0 has been officially released, are there any plans of having a 3-0-stable branch?

**Comment by rposborne** [comment]
+1

**Comment by JDutil** [comment]
The specs don't pass and should get fixed before another "stable" branch is created.

It looks like this might fix the failing 2-4-stable, but I'm unsure why the expectations are changing:
https://github.com/spree-contrib/spree_active_shipping/pull/206

Also need to apply this as well for Spree 3:
https://github.com/spree-contrib/spree_active_shipping/pull/209

**Comment by jspizziri** [comment]
https://github.com/spree-contrib/spree_active_shipping/pull/211

**Comment by JDutil** [comment]
Done thanks.
