### ISSUE TITLE
Add PO textbox

### ISSUE THREAD

**Issue by dbwinger** [spree-contrib/spree_active_shipping#225]

**Comment by jspizziri** [comment]
Can you please be a bit more specific? This doesn't really mean anything to me.

**Comment by jspizziri** [comment]
@dbwinger, I'm going to close this issue until you can provide more information. Please reference the contributing guidelines for more information:

https://github.com/spree-contrib/spree_active_shipping/blob/master/CONTRIBUTING.md

**Comment by dbwinger** [comment]
Oh shoot! That issue wasn't meant for this project.  So sorry for the confusion.
