### ISSUE TITLE
Question/Feature: Why are product_package measurements limited to type int?

### ISSUE THREAD

**Issue by Mrjaco12** [spree-contrib/spree_active_shipping#228]
It seems like it would be better for accuracy in shipping estimates, as well as be more agnostic to what kind of data I pass to the packages. I'm curious as to why the decision was made to make the measurement types int. I apologize if there is someone documentation somewhere discussing this issue but I couldn't find it. Thanks.

**Comment by jspizziri** [comment]
@Mrjaco12 ,

I wasn't around on this project when those decisions were made. I don't think that any of the contributors that were around when that decision was made are still engaged in the project, so I think it may be difficult to answer.

In regards to switching to a float for greater precision that would require some discussion with the existing community members, in addition to some research to see how viable it is as a solution. At that point it would require a PR to be submitted if there is interest.

**Comment by mleglise** [comment]
I also was not around when those decisions were made, but here's why I don't think it's worth changing it:

AFAIK, all carriers round package dimensions up to the nearest integer. I've yet to encounter a single case where the carrier APIs do *anything* with a decimal dimension other than round up. If you have an example case where adding decimal support would make an impact on the data returned by a carrier, then I think it would be worthwhile.

**Comment by Mrjaco12** [comment]
I am not aware of any examples in which a carrier takes precise measurements into account. Rather the PIM from which we were importing our data for packages was passing floats so we were seeing Spree throw errors on the import. I'm fine with massaging our data before we put it into Spree.
