### ISSUE TITLE
Backports needed to stable branches

### ISSUE THREAD

**Issue by mleglise** [spree-contrib/spree_active_shipping#229]
It looks like several improvements have been made, but exist only in different branches.
- master has a few items that could be backported to 3-0-stable
- 2-4-stable has my "convert_package_to_dimensions_array" placeholder, which could be merged into 2-3-stable, 3-0-stable, and master

Is anyone taking charge of this? I'd be happy to sort it out, but this seems less like an issue of pull requests and more just someone with access to spree-contrib to do the cleanup. @jspizziri is that you?

**Comment by jspizziri** [comment]
@mleglise, I think I'm the only contributor who is actively (at least attempting) to maintain this project at this point, so yea, I think it would be me. I'll try to make some time to do the backports.

On a side note, as you seem to have a high interest in this project as well, how would you feel about becoming a contributor? I would love to not be the only one actively maintaining it.

**Comment by mleglise** [comment]
Count me in. I do a fair bit of work on top of this library, and I'd like
to see it kept up.

-Marc

**Comment by jspizziri** [comment]
@JDutil, could you invite @mleglise to this team?

**Comment by JDutil** [comment]
Done

**Comment by mleglise** [comment]
Thanks guys. I've backported / merged several changes to branches: master, 3-0-stable, 2-4-stable, and 2-3-stable.
