### ISSUE TITLE
ActiveShipping::ResponseError not appropriately caught

### ISSUE THREAD

**Issue by darbs** [spree-contrib/spree_active_shipping#235]
Response errors are not appropriately caught in [base.rb](https://github.com/spree-contrib/spree_active_shipping/blob/master/app/models/spree/calculator/shipping/active_shipping/base.rb#L97-128). 

Active shipping raises a ```ActiveShipping::ResponseError``` which inherits from ```ActiveShipping::Error``` not ```ActiveMerchant::ActiveMerchantError``` so the errors are not caught. This causes the error to pass through and an error 500 instead of gracefully failing when entering incorrect address info for an order placed through spree admin. 

To reproduce simply place an order with an invalid address (I used South Carolina with zipcode 33716) or simply update the test in [active_shipping_calculator_spec.rb](https://github.com/spree-contrib/spree_active_shipping/blob/cb52b70fbadf06dd01173483d314868432469a18/spec/models/active_shipping_calculator_spec.rb#L87-96) to:

```ruby
      context "when there is an error retrieving the rates" do
        before do
          # expect(carrier).to receive(:find_rates).and_raise(ActiveMerchant::ActiveMerchantError)
          expect(carrier).to receive(:find_rates).and_raise(ActiveShipping::ResponseError)
        end

        it "should return false" do
          expect(calculator.available?(package)).to be(false)
        end
      end
```

**Comment by mleglise** [comment]
Confirmed. @darbs any chance you could put together a pull request with the fix?

**Comment by darbs** [comment]
@mleglise can do.
