### ISSUE TITLE
Feature Request/Proposition : Handling shipments / shipping labels

### ISSUE THREAD

**Issue by dangerdogz** [spree-contrib/spree_active_shipping#239]
I am currently in the process of integrating this feature (it's somewhat done but still some rough edges and it needs more test coverage)

Is this something that the maintainers would like to integrate to the extension? Same with receipts and "details". 

I need to handle shipping from the Spree backend in my current project so it means creating shipments and printing label/receipts. The backbone is already there since it's built in with ActiveShipping

Just wondering if this is something that could be useful to others there,  I am willing to develop it myself since I am already in the middle of it

**Comment by tanmay3011** [comment]
@dangerdogz Can you raise a PR for this.

**Comment by dangerdogz** [comment]
After consideration I think this is something largely outside the scope of this extension. It should be added to Spree or at the very least in another dedicated extension.
