### ISSUE TITLE
Spree Active Shipping Error - undefined method `iso' for nil:NilClass

### ISSUE THREAD

**Issue by NorCalDavid** [spree-contrib/spree_active_shipping#243]
I am getting this error after installing Spree Active Shipping, I am not having any luck finding a solution and I am hoping that you can point me in the right direction

**Comment by NorCalDavid** [comment]
Found the solution in another post.  Has to do with not having a default Stock Location set.

**Comment by vishal-bacancy** [comment]
@NorCalDavid 
can you please send me that post link? i am getting same issue

**Comment by ericnordelo** [comment]
Please, link to the post.
