### ISSUE TITLE
Make shipping methods have their own credentials

### ISSUE THREAD

**Issue by geermc4** [spree-contrib/spree_active_shipping#69]
On a talk with @GeekOnCoffee at spreeconf we talked about how with the addition of warehouses, it is not unlikely for people to try and use it for warehouses in different countries, problem is that the current implementation only allows for 1 FedEx key (or any other carrier) and at least for FedEx, you need a different key for the other country.

The options we discussed where...
1- Have a section to define carriers and set their keys and then on the shipping method, select which carrier to use.
2- Just have the credentials with the shipping method, although less DRY, easier to implement

Just leaving this here for discussion.

**Comment by jspizziri** [comment]
@geermc4, whats the status of this?

**Comment by geermc4** [comment]
We moved away from this approach unfortunately
